### ISSUE TITLE
IMD not working on spigot

### ISSUE THREAD

**Issue by Beeeeeeean** [CloudOn9/InstaMineDeepslate#19]
whatever i do in the command, even if i do the command you told me to do, it just tell me ''/imd [enable/disable]'' whaterver i do and the insta mine didint work /:

**Comment by Cloudate9** [comment]
I'm sorry to hear that you're having trouble :( May I confirm that you are using a netherite pickaxe with efficiency V, and haste II?

**Comment by Beeeeeeean** [comment]
yep, a netherite pickaxe with: silk touch, effeciency V, unbreaking 3, menidng, a gold beacon with haste 2. do it need to be a fortune pick? and what is the command suppose to say?

**Comment by Cloudate9** [comment]
Nope, a fortune pick shouldn't be required. To confirm, you are trying to mine deepslate right? 

The message sent should be "[IMD] Operation success!" when you do the command

Furthermore, what server version (e.g. 1.18) and software (e.g. spigot, paper) are you running?

**Comment by Beeeeeeean** [comment]
yes i am mining deepslate. i use a 1.18.2 SPIGOT server

**Comment by Cloudate9** [comment]
Ah, that would probably explain it. Try again on a PaperMC server (or any of its forks, e.g. PurPurMc)

**Comment by Beeeeeeean** [comment]
oh F, ig i wont use it then
