### ISSUE TITLE
No sound when deepslate blocks are mined [Bug]

### ISSUE THREAD

**Issue by bensuperpc** [CloudOn9/InstaMineDeepslate#5]
**Describe the bug**
There should be sounds when deepslate blocks are mined

**To Reproduce**
1. Download and install plugin
2. Mining deep slate with Netherite pickaxe, with Efficiency 5, Fortune 3... With Haste II
3. Instant mining but no sounds

**Expected behavior**
There should be sounds when deepslate blocks are mined, like when mining stone

**Additional context**
Tested Paper 1.18.1 or Purpur 1.18.1

**Comment by Cloudate9** [comment]
Sorry about that! I'll fix the sound, and it should be out in v1.0.2

**Comment by Cloudate9** [comment]
Officially fixed in Version 2.0.0. Curseforge should release the .jar soon, which you can get [here](https://www.curseforge.com/minecraft/bukkit-plugins/insta-mine-deepslate),
